package com.mal.assignment.accounts.domain.models;

public enum FailureReason {
    UNKNOWN_ACCOUNT,
    INSUFFICIENT_AVAILABLE_BALANCE,
    UNKNOWN_AUTHORIZATION,
    NOT_REVERSIBLE,
    ALREADY_REVERSED,
    CONCURRENT_MODIFICATION,
    INVALID_COMMAND,
    SETTLEMENT_REJECTED,
    INVALID_DAILY_RATE,
    UNSUPPORTED_ROUNDING_MODE,
    INVALID_SPLIT_PARTS,
    MISSING_OVERDRAFT_FEE,
    INVALID_OVERDRAFT_POLICY,
    UNKNOWN_CURRENCY,
    MISSING_LEDGER_CONFIG,
    CONFIG_LOAD_FAILED,
    UNIT_OF_WORK_ALREADY_COMMITTED,
    UNKNOWN_COMMAND_HANDLER
}
